language: cpp

matrix:
  include:
    - os: linux
      dist: focal

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/ppa
  - sudo apt update -qq

install:
  - sudo apt install -qq cmake g++-11
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 90

before_script:
  - cmake -B build

script:
  - cmake --build build -- -j $(nproc)
  - ./build/jpeg2000
