language: cpp

os:
  - linux

install:
  - sudo apt purge --auto-remove cmake
  - pip3.8 install -U cmake

before_script:
  - eval "$MATRIX_EVAL"
  - if [ "$BUILD_TESTS" = "ON" ]; then python3.8 -m venv venv; . ./venv/bin/activate; pip install -r requirements.txt; fi
  - cmake -DBUILD_TESTS="$BUILD_TESTS" -B build

matrix:
  include:
    - os: linux
      dist: focal
      name: "gcc main app"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-ppa
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
      install:
        - python3 -m pip install -U --user pip
      script:
        - cmake --build build -- -j $(nproc)
        - ./build/jpeg2000
    - os: linux
      dist: focal
      name: "gcc dwt tests"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-ppa
          packages:
            - g++-10
            - python3-venv
      env:
        - BUILD_TESTS="ON"
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
      install:
        - python3 -m pip install -U --user pip
      script:
        - cmake --build build --target install -- -j $(nproc)
        - pytest ./test/test.py
    - os: linux
      dist: bionic
      name: "clang main app"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - python3.8
            - python3.8-dev
            - python3.8-distutils
            - llvm-12-dev
            - libclang-12-dev
            - clang-tools-12
            - clang-12
            - lld-12
            - libc++-12-dev
            - libc++abi-12-dev
      env:
        - MATRIX_EVAL="CC=clang-12 && CXX=clang++-12"
      install:
        - wget https://bootstrap.pypa.io/get-pip.py
        - sudo python3.8 get-pip.py
      script:
        - cmake --build build -- -j $(nproc)
        - ./build/jpeg2000
    - os: linux
      dist: bionic
      name: "clang dwt tests"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - python3.8
            - python3.8-dev
            - python3.8-distutils
            - python3.8-venv
            - llvm-12-dev
            - libclang-12-dev
            - clang-tools-12
            - clang-12
            - lld-12
            - libc++-12-dev
            - libc++abi-12-dev
      env:
        - BUILD_TESTS="ON"
        - MATRIX_EVAL="CC=clang-12 && CXX=clang++-12"
      install:
        - wget https://bootstrap.pypa.io/get-pip.py
        - sudo python3.8 get-pip.py
      script:
        - cmake --build build --target install -- -j $(nproc)
        - pytest ./test/test.py
