language: cpp

matrix:
  include:
    - os: linux
      dist: focal

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/ppa
  - sudo apt update -qq

install:
  - sudo apt install -qq g++-10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90
  - sudo apt remove cmake
  - pip install cmake --upgrade

before_script:
  - cmake -B build

script:
  - cmake --build build -- -j $(nproc)
  - ./build/jpeg2000
