language: cpp

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/ppa
  - sudo apt update -qq

install:
  - sudo apt install -qq g++-10 python3-venv
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90
  - sudo apt remove cmake
  - python3 -m pip install --user --upgrade pip
  - pip3 install cmake --upgrade

before_script:
  - if [ "$COMPILER" = "clang" ]; then wget https://apt.llvm.org/llvm.sh; chmod +x llvm.sh; sudo ./llvm.sh 11; fi
  - if [ "$BUILD_TESTS" = "ON" ]; then python3 -m venv venv; . ./venv/bin/activate; pip install -r requirements.txt; fi
  - if [ "$COMPILER" = "gcc" ]; then cmake -DBUILD_TESTS="$BUILD_TESTS" -B build; fi
  - if [ "$COMPILER" = "clang" ]; then cmake -DBUILD_TESTS="$BUILD_TESTS" -DCMAKE_C_COMPILER=clang-11 -DCMAKE_CXX_COMPILER=clang++-11 -B build; fi

matrix:
  include:
    - os: linux
      dist: focal
      name: "App main"
      env:
        - COMPILER="gcc"
      script:
        - cmake --build build -- -j $(nproc)
        - ./build/jpeg2000
    - os: linux
      dist: focal
      name: "Tests dwt"
      env:
        - BUILD_TESTS="ON"
        - COMPILER="gcc"
      script:
        - cmake --build build --target install -- -j $(nproc)
        - pytest ./test/test.py
    - os: linux
      dist: focal
      name: "App main"
      env:
        - COMPILER="clang"
      script:
        - cmake --build build -- -j $(nproc)
        - ./build/jpeg2000
    - os: linux
      dist: focal
      name: "Tests dwt"
      env:
        - BUILD_TESTS="ON"
        - COMPILER="clang"
      script:
        - cmake --build build --target install -- -j $(nproc)
        - pytest ./test/test.py
