language: cpp

os:
  - linux

install:
  - if [ "$COMPILER" = "gcc" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90; fi
  - sudo apt remove cmake
  - if [ "$COMPILER" = "clang" ]; then wget https://bootstrap.pypa.io/get-pip.py; sudo python3.8 get-pip.py; fi
  - python3.8 -m pip install --user --upgrade pip
  - pip3.8 install cmake --upgrade

before_script:
  - if [ "$BUILD_TESTS" = "ON" ]; then python3.8 -m venv venv; . ./venv/bin/activate; pip install -r requirements.txt; fi
  - if [ "$COMPILER" = "gcc" ]; then cmake -DBUILD_TESTS="$BUILD_TESTS" -B build; fi
  - if [ "$COMPILER" = "clang" ]; then cmake -DBUILD_TESTS="$BUILD_TESTS" -DCMAKE_C_COMPILER=clang-12 -DCMAKE_CXX_COMPILER=clang++-12 -B build; fi

matrix:
  include:
    - os: linux
      dist: focal
      name: "gcc main app"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-ppa
          packages:
            - g++-10
      env:
        - COMPILER="gcc"
      script:
        - cmake --build build -- -j $(nproc)
        - ./build/jpeg2000
    - os: linux
      dist: focal
      name: "gcc dwt tests"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-ppa
          packages:
            - g++-10
            - python3-venv
      env:
        - BUILD_TESTS="ON"
        - COMPILER="gcc"
      script:
        - cmake --build build --target install -- -j $(nproc)
        - pytest ./test/test.py
    - os: linux
      dist: bionic
      name: "clang main app"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - python3.8
            - python3.8-dev
            - python3.8-distutils
            - llvm-12-dev
            - libclang-12-dev
            - clang-tools-12
            - clang-12
            - lld-12
            - libc++-12-dev
            - libc++abi-12-dev
      env:
        - COMPILER="clang"
      script:
        - cmake --build build -- -j $(nproc)
        - ./build/jpeg2000
    - os: linux
      dist: bionic
      name: "clang dwt tests"
      addons:
        apt:
          update: true
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - python3.8
            - python3.8-dev
            - python3.8-distutils
            - python3.8-venv
            - llvm-12-dev
            - libclang-12-dev
            - clang-tools-12
            - clang-12
            - lld-12
            - libc++-12-dev
            - libc++abi-12-dev
      env:
        - BUILD_TESTS="ON"
        - COMPILER="clang"
      script:
        - cmake --build build --target install -- -j $(nproc)
        - pytest ./test/test.py
