name: Build docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/szymonzos/ubuntu-opencv:master
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        build_type: # [build_type, sanitizer]
          - [ Release, OFF ]
          - [ Debug, ASAN ]
          - [ Debug, MSAN ]
          - [ Debug, TSAN ]
        exclude:
          - compiler: gcc
            build_type: [ Debug, MSAN ]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure compiler
        run: ./ci/config_compiler.sh ${{matrix.compiler}}

      - name: Configure CMake
        run: >
          cmake -B ./build
          -DCMAKE_BUILD_TYPE=${{matrix.build_type[0]}}
          -DCMAKE_C_COMPILER=${{env.CC}}
          -DCMAKE_CXX_COMPILER=${{env.CXX}}
          -DBUILD_TESTS=ON
          -DUSE_SANITIZERS=${{matrix.build_type[1]}}

      - name: Build
        run: >
          cmake --build ./build
          --config ${{matrix.build_type[0]}}
          --target jpeg2000 jpeg2000_test jpeg2000_ut install -- -j $(nproc)

      - name: Main app
        run: ./ci/run_main_app.sh

      - name: Unit Tests
        run: ./build/bin/jpeg2000_ut

      - name: Acceptance Tests
        run: |
          . ./build/export_asan_config.sh 2> /dev/null || true
          pytest -s ./test/test.py
