name: Build docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/szymonzos/ubuntu-opencv:master
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        build_type: [ Release, Debug ]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure compiler
        run: ./ci/config_compiler.sh ${{matrix.compiler}}

      - name: Configure CMake
        run: >
          USE_SANITIZERS=${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }} &&
          cmake -B ./build
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          -DCMAKE_C_COMPILER=${{env.CC}}
          -DCMAKE_CXX_COMPILER=${{env.CXX}}
          -DBUILD_TESTS=ON
          -DUSE_SANITIZERS="$USE_SANITIZERS"

      - name: Build
        run: >
          cmake --build ./build
          --config ${{matrix.build_type}}
          --target jpeg2000 jpeg2000_test jpeg2000_ut install -- -j $(nproc)

      - name: Main app
        run: ./ci/run_main_app.sh

      - name: Unit Tests
        run: ./build/bin/jpeg2000_ut

      - name: Acceptance Tests
        run: |
          . ./build/export_asan_config.sh 2> /dev/null || true
          pytest -s ./test/test.py
