name: Build docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/szymonzos/ubuntu-opencv:master
    strategy:
      matrix:
        compiler: [ gcc, clang ]
        build_type: [ Release, Debug ]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure compiler
        run: ./ci/config_compiler.sh ${{matrix.compiler}}

      - name: Configure CMake
        run: >
          cmake -B ./build
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          -DCMAKE_C_COMPILER=${{env.CC}}
          -DCMAKE_CXX_COMPILER=${{env.CXX}}
          -DBUILD_TESTS=ON
          -DUSE_SANITIZERS=ON

      - name: Build
        run: >
          cmake --build ./build
          --config ${{matrix.build_type}}
          --target jpeg2000 jpeg2000_test jpeg2000_ut install -- -j $(nproc)

      - name: Main app
        run: ./ci/run_main_app.sh

      - name: Unit Tests
        run: ./build/bin/jpeg2000_ut

      # Investigate if it is possible to run sanitizers only on shared lib
      # https://stackoverflow.com/a/55692977
      # export LD_PRELOAD=$(gcc-11 -print-file-name=libasan.so)
      - name: Acceptance Tests
        run: |
          export ASAN_OPTIONS=verify_asan_link_order=0         
          pytest -s ./test/test.py
